---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-tls
  namespace: cilium
spec:
  secretName: hubble-server-tls
  dnsNames:
    - "hubble.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-clouddns
