---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: 10.91.1.9
  - target:
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: 10.91.1.9
  - target:
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/env/2/value
        value: 10.91.1.9
  - target:
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/4/env/3/value
        value: 10.91.1.9
