---
# yamllint disable rule:line-length
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keydb-operator
  name: keydb-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keydb-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: keydb-operator-controller-manager
    namespace: keydb-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keydb-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keydb-operator-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: keydb-operator-controller-manager
    namespace: keydb-operator-system
