---
# yamllint disable rule:line-length
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-operator-keydb-editor-role
rules:
  - apiGroups:
      - keydb.krestomat.io
    resources:
      - keydbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keydb.krestomat.io
    resources:
      - keydbs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-operator-keydb-viewer-role
rules:
  - apiGroups:
      - keydb.krestomat.io
    resources:
      - keydbs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - keydb.krestomat.io
    resources:
      - keydbs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keydb.krestomat.io
    resources:
      - keydbs
      - keydbs/status
      - keydbs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-operator-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
