---
# yamllint disable rule:line-length
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keydb-operator
  name: keydb-operator-leader-election-rolebinding
  namespace: keydb-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keydb-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: keydb-operator-controller-manager
    namespace: keydb-operator-system
