---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keydb-operator
  name: keydb-operator-controller-manager
  namespace: keydb-operator-system
