---
steamdeck:
  hosts:
    deck:
      ansible_user: deck
      ansible_host: dronenb-steamdeck
      ansible_become_pass: >-
            {{
              lookup(
                'community.general.bitwarden',
                'deck_become_pass',
                field='password'
              ) |
              first
            }}
      pacman_packages:
        - fuseiso
      flatpaks:
        - net.lutris.Lutris
        - org.prismlauncher.PrismLauncher
        - com.heroicgameslauncher.hgl
