---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-server-tls
  namespace: netbox
spec:
  secretName: netbox-server-tls
  dnsNames:
    - "netbox.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-clouddns
