---
# yamllint disable rule:line-length
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-secrets-store-provider-gcp
  name: csi-secrets-store-provider-gcp
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-gcp
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-gcp
    spec:
      serviceAccountName: secrets-store-csi-driver-provider-gcp
      initContainers:
        - name: chown-provider-mount
          image: busybox
          command:
            - chown
            - 1000:1000
            - /etc/kubernetes/secrets-store-csi-providers
          volumeMounts:
            - mountPath: /etc/kubernetes/secrets-store-csi-providers
              name: providervol
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
        - name: provider
          image: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin@sha256:cb0cb5e7abf9487619f2a55acf4c608c8c17599d1b889cc88cb73356740f846b
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            privileged: true
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: TARGET_DIR
              value: /etc/kubernetes/secrets-store-csi-providers
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/tokens/gcp-ksa/credential-configuration.json
          volumeMounts:
            - mountPath: /etc/kubernetes/secrets-store-csi-providers
              name: providervol
              mountPropagation: None
              readOnly: false
            - mountPath: /var/run/secrets/tokens/gcp-ksa
              name: gcp-ksa
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: 8095
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
      volumes:
        - name: providervol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: gcp-ksa
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: k3s
                  expirationSeconds: 3600
                  path: token
              - configMap:
                  items:
                    - key: credential-configuration.json
                      path: credential-configuration.json
                  name: default-creds-config
                  optional: false
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: linux
