---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: secrets-store-csi-driver
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: default-creds-config
    files:
      - config/credential-configuration.json
