---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-dashboard-tls
  namespace: rook-ceph
spec:
  secretName: ceph-dashboard-tls
  dnsNames:
    - "ceph.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
