---
repos:
  # v8.18.1 https://api.github.com/repos/gitleaks/gitleaks/tags
  - rev: dab7d0292ad7ebc52c7adfcad755f92e2f7c9a9a
    repo: https://github.com/gitleaks/gitleaks
    hooks:
      - id: gitleaks
        stages: [pre-commit]
  # v0.9.0.6 https://api.github.com/repos/shellcheck-py/shellcheck-py/tags
  - rev: 4de1378e4cd853bfc2b111b05fff35e2dbf809a3
    repo: https://github.com/shellcheck-py/shellcheck-py
    hooks:
      - id: shellcheck
        stages: [pre-commit]
  # v1.33.0 https://api.github.com/repos/adrienverge/yamllint/tags
  - rev: 8713140e99914c0cb6e07364daedfb140847c3c5
    repo: https://github.com/adrienverge/yamllint
    hooks:
      - id: yamllint
        stages: [pre-commit]
  # v3.1.0 https://api.github.com/repos/compilerla/conventional-pre-commit/tags
  - rev: 07fd005463366385a8b0fa97c8d2a25b5bac19e0
    repo: https://github.com/compilerla/conventional-pre-commit
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  # v0.38.0 https://api.github.com/repos/igorshubovych/markdownlint-cli/tags
  - rev: 1d2f2483dbca436b5e89d208f1ff56688ba4af9e
    repo: https://github.com/igorshubovych/markdownlint-cli
    hooks:
      - id: markdownlint
        stages: [pre-commit]
#   - repo: https://github.com/bridgecrewio/checkov.git
#     rev: '3.1.38'
#     hooks:
#       - id: checkov
#         verbose: false
#   - repo: https://github.com/ansible/ansible-lint.git
#     rev: v6.22.1
#     hooks:
#       - id: ansible-lint
#         files: \.(yaml|yml)$
#         name: Ansible Lint
#         description: Run configurations on .ansible-lint file
#         entry: python3 -m ansiblelint --force-color
#         always_run: false
#         additional_dependencies:
#           - "jmespath"
