---
repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # frozen: v8.8.0
    hooks:
      - id: megalinter-full # Slower, more thorough
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7c1022b54dcb1d1911e6c885089940e8499f0253 # frozen: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
