---
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: 145400593c178304246371bc45290588bc72f43e  # frozen: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/adrienverge/yamllint.git
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6  # frozen: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 4efeb931d635ed3e57749de4326b752b345c8372  # frozen: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 88f5e62afbc373fb23bdf78010adab5e8b37ee98  # frozen: v0.40.0
    hooks:
      - id: markdownlint
  # - repo: https://github.com/bridgecrewio/checkov.git
  #   rev: '3.1.38'
  #   hooks:
  #     - id: checkov
  #       verbose: false
  # v3.1.0 https://api.github.com/repos/compilerla/conventional-pre-commit/tags
  # - repo: https://github.com/ansible/ansible-lint.git
  #   rev: v6.22.1
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       name: Ansible Lint
  #       description: Run configurations on .ansible-lint file
  #       entry: python3 -m ansiblelint --force-color
  #       always_run: false
  #       additional_dependencies:
  #         - "jmespath"
