---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: nfs-subdir-external-provisioner
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - storageclass.yaml
