apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: netbox-postgresql
  namespace: netbox
spec:
  crVersion: 2.7.0
  users:
    - name: netbox
      databases:
        - netbox
      options: "SUPERUSER"
      password:
        type: ASCII
      secretName: "netbox-postgresql-credentials"
  # https://docs.percona.com/percona-operator-for-postgresql/2.0/images.html
  # curl -sL curl https://check.percona.com/versions/v1/pg-operator/2.7.0 | jq
  image: docker.io/percona/percona-postgresql-operator:2.7.0-ppg17.5.2-postgres@sha256:cfb99ebeec00ab6efb4fca4a8da2b8c3b489dd792bd2f907848197ba09bc9553
  imagePullPolicy: Always
  postgresVersion: 17
  instances:
    - name: instance1
      replicas: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/data: postgres
                topologyKey: kubernetes.io/hostname
      dataVolumeClaimSpec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  proxy:
    pgBouncer:
      replicas: 1
      # https://docs.percona.com/percona-operator-for-postgresql/2.0/images.html
      image: docker.io/percona/percona-pgbouncer:1.24.1@sha256:451431afa3cd288ecda92b6446bec8833fbf376fbd1b7c7e314fc42f3355255f
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/role: pgbouncer
                topologyKey: kubernetes.io/hostname
  backups:
    pgbackrest:
      # https://docs.percona.com/percona-operator-for-postgresql/2.0/images.html
      image: docker.io/percona/percona-pgbackrest:2.55.0@sha256:b0d2defbc7a07cf395b1fa6c6e13d9d3267c3a2d3c52362ac440db26ea4a4bad
      repoHost:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      postgres-operator.crunchydata.com/data: pgbackrest
                  topologyKey: kubernetes.io/hostname
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: nfs-client
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
