---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: secrets-store-csi-driver
resources:
  - ../../base
  - secretproviderclass.yaml
  - pod.yaml
patches:
  - target:
      kind: DaemonSet
      name: csi-secrets-store-provider-gcp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.fh.dronen.house/secrets-store-csi-driver-provider-gcp:newarch
