---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - storageclass.yaml
