---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: <path:projects/805422933562/secrets/email#email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: <path:projects/805422933562/secrets/email#email>
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
