---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  serviceAccount: default
  containers:
    - image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
      imagePullPolicy: IfNotPresent
      name: mypod
      resources:
        requests:
          cpu: 100m
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      command: ["/usr/bin/sleep", "inf"]
      volumeMounts:
        - mountPath: "/var/gcpsecrets"
          name: gcpsecrets
        - mountPath: "/var/azuresecrets"
          name: azuresecrets
        - mountPath: "/var/awssecrets"
          name: awssecrets
  volumes:
    - name: gcpsecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "gcp"
    - name: azuresecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure"
    - name: awssecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws"
