apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../base
  - ./clusterissuer.yaml
configMapGenerator:
  - name: default-creds-config
    namespace: cert-manager
    files:
      - config/credential-configuration.json
