---
# yamllint disable rule:line-length
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hubble-generate-certs
  namespace: cilium
  labels:
    k8s-app: hubble-generate-certs
    app.kubernetes.io/name: hubble-generate-certs
    app.kubernetes.io/part-of: cilium
spec:
  schedule: 0 0 1 */4 *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: hubble-generate-certs
        spec:
          containers:
            - name: certgen
              image: quay.io/cilium/certgen:v0.1.12@sha256:bbc5e65e9dc65bc6b58967fe536b7f3b54e12332908aeb0a96a36866b4372b4e
              imagePullPolicy: IfNotPresent
              command:
                - /usr/bin/cilium-certgen
              args:
                - --cilium-namespace=cilium
                - --ca-generate
                - --ca-reuse-secret
                - --hubble-server-cert-generate
                - --hubble-server-cert-common-name=*.default.hubble-grpc.cilium.io
                - --hubble-server-cert-validity-duration=94608000s
                - --hubble-relay-client-cert-generate
                - --hubble-relay-client-cert-validity-duration=94608000s
          hostNetwork: true
          serviceAccount: hubble-generate-certs
          serviceAccountName: hubble-generate-certs
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          affinity:
      ttlSecondsAfterFinished: 1800
