---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - cronjob.yaml
  - daemonset.yaml
  - deployment.yaml
  - endpoints.yaml
  - gatewayclass.yaml
  - ingressclass.yaml
  - job.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
