---
# yamllint disable rule:line-length
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-secrets
  labels:
    app.kubernetes.io/part-of: cilium
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
