---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium
  namespace: cilium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-operator
  namespace: cilium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-relay
  namespace: cilium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-ui
  namespace: cilium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-generate-certs
  namespace: cilium
