---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: f5-ipam-controller
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - serviceaccount.yaml
