---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../../base
patches:
  - target:
      kind: StorageClass
      name: nfs-client
    patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: true
