---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  # https://quay.io/repository/argoproj/argocd?tab=tags
  version: "sha256:42a488667bc07b70b16a672f632a5d3f484a262ae5f66b5d161c5be2d905db2f"
  server:
    ingress:
      enabled: false
    insecure: false
