---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  # https://quay.io/repository/argoproj/argocd?tab=tags
  version: "sha256:68894064bc381c19ea951029510aa614bd26bf46c2ec65ea445c7d8d095a9417"
  server:
    ingress:
      enabled: false
    insecure: false
