---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  version: "sha256:c3edbf13bade98e4ebfb015ad219c89f1b7c9454fae07e8fc3245a23e50b0955"
  server:
    ingress:
      enabled: false
    insecure: false
