---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  extraConfig:
    # https://github.com/argoproj/argo-cd/issues/10456#issuecomment-1249381338
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
  server:
    ingress:
      enabled: false
    insecure: false
  # https://quay.io/repository/argoproj/argocd?tab=tags
  version: "sha256:19ba7f44cba487c4a0c98ac336327c4df04383dff84f87ea1a578972eb62dd17" # v3.1.8
