---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  # https://quay.io/repository/argoproj/argocd?tab=tags
  version: "sha256:86207008e5230744c2262c67d43efd9df031863141b82d9b9fe5945c74d46c15"
  server:
    ingress:
      enabled: false
    insecure: false
