apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opnsense-unbound-external-dns-webhook-viewer
  labels:
    helm.sh/chart: external-dns-1.19.0
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/version: 0.19.0
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opnsense-unbound-external-dns-webhook
subjects:
  - kind: ServiceAccount
    name: opnsense-unbound-external-dns-webhook
    namespace: external-dns
