apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-unbound-external-dns-webhook
  namespace: external-dns
  labels:
    helm.sh/chart: external-dns-1.15.2
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/version: 0.15.1
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/instance: external-dns
    spec:
      serviceAccountName: opnsense-unbound-external-dns-webhook
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: external-dns
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=debug
            - --log-format=text
            - --interval=1m
            - --source=ingress
            - --source=service
            - --policy=sync
            - --registry=txt
            - --txt-owner-id=default
            - --txt-prefix=k8s.
            - --domain-filter=fh.dronen.house
            - --provider=webhook
            - --ignore-ingress-tls-spec
            - --webhook-provider-url=http://localhost:8800
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        - name: webhook
          image: ghcr.io/jobs62/opnsense_unbound_external-dns_webhook:v0.4.5@sha256:22d3bd25bacaa0a8445a746d6541a8994bcb54e6047f5a079574adc792f88034
          imagePullPolicy: IfNotPresent
          env:
            - name: OPNSENSE_BASE
              value: https://10.91.1.1/
            - name: OPNSENSE_ALLOW_INVALID_CERTS
              value: "true"
            - name: OPNSENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: opnsense-creds
            - name: OPNSENSE_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: opnsense-creds
          ports:
            - name: http-webhook
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http-webhook
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http-webhook
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
