apiVersion: v1
kind: ServiceAccount
metadata:
  name: opnsense-unbound-external-dns-webhook
  namespace: external-dns
  labels:
    helm.sh/chart: external-dns-1.19.0
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/version: 0.19.0
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
