---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    helm.sh/chart: external-dns-1.14.5
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/version: 0.14.2
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken:
