---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
  name: opnsense-creds
  namespace: external-dns
type: Opaque
stringData:
  key: <path:projects/805422933562/secrets/opnsense-key#opnsense-key>
  secret: <path:projects/805422933562/secrets/opnsense-secret#opnsense-secret>
