apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - namespace.yaml
  - serviceaccount.yaml
namespace: secrets-store-csi-driver
