---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: cert-manager
resources:
  - clusterissuer.yaml
  - secret.yaml
configMapGenerator:
  - name: default-creds-config
    files:
      - config/credential-configuration.json
    options:
      disableNameSuffixHash: true
