---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <path:projects/805422933562/secrets/cert-manager-cloudflare-token#cert-manager-cloudflare-token>
