---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - certificate.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - middleware.yaml
  - ingressroute.yaml
