---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
