apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  authentication:
    passwordFromSecret:
      name: redis-password
      key: redis-password
  # https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly
  image: ghcr.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 750Mi
    requests:
      cpu: 15m
      memory: 50Mi
