apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  replicas: 1
  resources:
    requests:
      cpu: 15m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 750Mi
  authentication:
    passwordFromSecret:
      name: redis-password
      key: redis-password
