apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  authentication:
    passwordFromSecret:
      name: redis-password
      key: redis-password
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.28.1
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 750Mi
    requests:
      cpu: 15m
      memory: 50Mi
