apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  refreshInterval: "0"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: netbox-redis
  target:
    name: redis-password
    template:
      type: Opaque
      data:
        redis-password: "{{ .password }}"
