apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
