---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  secretName: home-assistant-cert
  dnsNames:
    - "home-assistant.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
