apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-config
  namespace: netbox
spec:
  refreshInterval: "30m"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: django-secret-key
  target:
    name: netbox-config
    template:
      type: Opaque
      data:
        secret_key: "{{ .password }}"
        email_password: ""
