apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keydb-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dronenb/HomeLab.git"
    targetRevision: HEAD
    path: kubernetes/workloads/keydb-operator/manifests/overlays/fh
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keydb-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
