apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dronenb/HomeLab.git"
    targetRevision: HEAD
    path: kubernetes/workloads/olm/manifests/overlays/fh
  destination:
    server: "https://kubernetes.default.svc"
    namespace: olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
