apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dronenb/HomeLab.git"
    targetRevision: HEAD
    path: kubernetes/workloads/system-upgrade-controller/manifests/overlays/fh
  destination:
    server: "https://kubernetes.default.svc"
    namespace: system-upgrade-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
