---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-cert
  dnsNames:
    - "argocd.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
