apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - customresourcedefinition.yaml
  - deployment-cert-manager-cainjector.yaml
  - deployment-cert-manager-webhook.yaml
  - deployment-cert-manager.yaml
  - mutatingwebhookconfiguration.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
  - validatingwebhookconfiguration.yaml
