---
# yamllint disable rule:line-length
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: percona-postgresql
  labels:
    helm.sh/chart: pg-operator-2.7.0
    app.kubernetes.io/name: pg-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.7.0
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: release-name
    meta.helm.sh/release-namespace: percona-postgresql
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints/restricted
      - pods/exec
      - services
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - watch
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgbackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgbackups/finalizers
      - perconapgclusters/status
      - perconapgrestores/status
      - perconapgupgrades/finalizers
      - perconapgupgrades/status
    verbs:
      - patch
      - update
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgbackups/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgclusters
      - perconapgupgrades
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - pgv2.percona.com
    resources:
      - perconapgrestores
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - crunchybridgeclusters
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - crunchybridgeclusters/finalizers
      - crunchybridgeclusters/status
    verbs:
      - patch
      - update
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - pgadmins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - pgadmins/finalizers
      - pgupgrades/finalizers
      - postgresclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - pgadmins/status
      - pgupgrades/status
    verbs:
      - patch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - pgupgrades
      - postgresclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
