---
# yamllint disable rule:line-length
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: percona-postgresql
  labels:
    helm.sh/chart: pg-operator-2.7.0
    app.kubernetes.io/name: pg-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.7.0
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: release-name
    meta.helm.sh/release-namespace: percona-postgresql
subjects:
  - kind: ServiceAccount
    name: percona-postgresql
    namespace: percona-postgresql
roleRef:
  kind: ClusterRole
  name: percona-postgresql
  apiGroup: rbac.authorization.k8s.io
