---
# yamllint disable rule:line-length
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-pg-operator
  namespace: percona-postgresql
  labels:
    helm.sh/chart: pg-operator-2.5.1
    app.kubernetes.io/name: pg-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.5.1
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: release-name
    meta.helm.sh/release-namespace: percona-postgresql
    pgv2.percona.com/control-plane: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      pgv2.percona.com/control-plane: postgres-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: pg-operator
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/part-of: pg-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: pg-operator
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/part-of: pg-operator
        pgv2.percona.com/control-plane: postgres-operator
    spec:
      serviceAccountName: release-name-pg-operator
      terminationGracePeriodSeconds: 600
      containers:
        - name: percona-postgresql-operator
          image: percona/percona-postgresql-operator:2.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          env:
            - name: PGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_STRUCTURED
              value: "false"
            - name: LOG_LEVEL
              value: INFO
            - name: DISABLE_TELEMETRY
              value: "false"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 20Mi
