---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - customresourcedefinition.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
