---
# yamllint disable rule:line-length
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-pg-operator
  namespace: percona-postgresql
  labels:
    helm.sh/chart: pg-operator-2.5.1
    app.kubernetes.io/name: pg-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.5.1
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: release-name
    meta.helm.sh/release-namespace: percona-postgresql
subjects:
  - kind: ServiceAccount
    name: release-name-pg-operator
roleRef:
  kind: Role
  name: release-name-pg-operator
  apiGroup: rbac.authorization.k8s.io
