apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netbox
  labels:
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.4.5
    helm.sh/chart: netbox-7.1.18
  namespace: netbox
roleRef:
  kind: Role
  name: netbox
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: netbox
    namespace: netbox
