apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: netbox
  namespace: netbox
  labels:
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.2.6
    helm.sh/chart: netbox-5.0.57
