---
# yamllint disable rule:line-length
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-upgrade
  namespace: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-upgrade-controller
subjects:
  - kind: ServiceAccount
    name: system-upgrade
    namespace: system-upgrade
