---
# yamllint disable rule:line-length
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: valkey-operator
  name: valkey-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: valkey-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: valkey-operator-controller-manager
    namespace: valkey-operator-system
