---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: valkey-operator
  name: valkey-operator-controller-manager
  namespace: valkey-operator-system
