apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nmstate-operator
  namespace: nmstate
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
