---
# yamllint disable rule:line-length
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: f5-bigip-ctlr
  labels:
    app.kubernetes.io/instance: f5-bigip-ctlr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.32
    release: f5-bigip-ctlr
    heritage: Helm
rules:
  - apiGroups:
      - ""
      - extensions
      - networking.k8s.io
      - route.openshift.io
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - ingresses
      - pods
      - ingressclasses
      - policies
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - extensions
      - networking.k8s.io
      - route.openshift.io
    resources:
      - configmaps
      - events
      - ingresses/status
      - services/status
      - routes/status
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - cis.f5.com
    resources:
      - virtualservers
      - virtualservers/status
      - tlsprofiles
      - transportservers
      - transportservers/status
      - ingresslinks
      - ingresslinks/status
      - externaldnses
      - policies
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io/v1
    resources:
      - network
    verbs:
      - list
  - apiGroups:
      - fic.f5.com
    resources:
      - ipams
      - ipams/status
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
