---
# yamllint disable rule:line-length
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-bigip-ctlr
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: f5-bigip-ctlr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.32
    release: f5-bigip-ctlr
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-bigip-ctlr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: f5-bigip-ctlr
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: f5-bigip-ctlr
        app: f5-bigip-ctlr
        release: f5-bigip-ctlr
    spec:
      serviceAccountName: k8s-bigip-ctlr
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: f5-bigip-ctlr
          image: f5networks/k8s-bigip-ctlr:2.18.0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 15
          volumeMounts:
            - name: bigip-creds
              mountPath: /tmp/creds
              readOnly: true
          imagePullPolicy: Always
          command:
            - /app/bin/k8s-bigip-ctlr
          args:
            - --ingress-class=f5
            - --credentials-directory
            - /tmp/creds
            - --bigip-partition=ben
            - --bigip-url=10.91.1.11
            - --ipam=true
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: bigip-creds
          secret:
            secretName: f5-bigip-ctlr-login
