---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: k8s-bigip-ctlr
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - customresourcedefinition.yaml
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - serviceaccount.yaml
