---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-bigip-ctlr
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: f5-bigip-ctlr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.32
    release: f5-bigip-ctlr
    heritage: Helm
