---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-server-tls
  namespace: registry
spec:
  secretName: registry-server-tls
  dnsNames:
    - "registry.fh.dronen.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
