---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: registry
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: registry-config
    namespace: registry
    files:
      - config/config.yaml
generatorOptions:
  disableNameSuffixHash: false
