---
# yamllint disable rule:line-length
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-static-provisioner-config
  namespace: local-static-provisioner
  labels:
    helm.sh/chart: local-static-provisioner-2.8.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
data:
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Block
