---
# yamllint disable rule:line-length
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets-store.csi.k8s.io
  labels:
    app.kubernetes.io/instance: csi-secrets-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.4.4
    app: secrets-store-csi-driver
    helm.sh/chart: secrets-store-csi-driver-1.4.4
spec:
  podInfoOnMount: true
  attachRequired: false
  volumeLifecycleModes:
    - Ephemeral
