---
# yamllint disable rule:line-length
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: secrets-store-csi-driver
  labels:
    app.kubernetes.io/instance: csi-secrets-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.4.5
    app: secrets-store-csi-driver
    helm.sh/chart: secrets-store-csi-driver-1.4.5
